### ISSUE TITLE
提示not enough values to unpack (expected 3, got 2) 

### ISSUE THREAD

**Issue by luoning** [Clover27/ancient-Chinese-poetry-generator#1]
直接用的test.py后

Traceback (most recent call last):
  File "./lstm/generate.py", line 57, in <module>
    main()
  File "./lstm/generate.py", line 38, in main
    [voc,voc_count,pz] = json.loads(voc_t.read())
ValueError: not enough values to unpack (expected 3, got 2)

文件里是不是缺了pz的信息呀

**Comment by Clover27** [comment]
Sorry about that. If you use the default argument for vocabulary, that file does not contain 'pz' object. Please use another updated vocabulary file like `model/weights-700-3-0.2/vocabulary.json` or use `preprocessing.py` to generate a vocabulary file.

**Comment by sharmer156** [comment]
python ./lstm/generate.py -p 春川雄帝 -s 春氣滿林香 -v ./model/weights-700-3-0.2/vocabulary.json -w model/weights/sample2-weights-512-0.2-3.4132.hdf5 -m ./model-512-0.2.h5
python ./lstm/generate.py -p 春川雄帝 -s 春氣滿林香 -v ./model/weights-700-3-0.2/vocabulary.json -w model/weights/sample-weights-256-0.2-2.1103.hdf5 -m ./model/weights/model-256-0.2.h5
python ./lstm/generate.py -p 春川雄帝 -s 春氣滿林香 -v ./model/weights-700-3-0.2/vocabulary.json -w model/weights/sample2-weights-512-0.2-3.4132.hdf5 -m ./model/weights/model-256-0.2.h5

ValueError: not enough values to unpack (expected 3, got 2)

**Comment by calmzealA** [comment]
自己运行一下preprocessing和train ，然后使用生成的文件就行。
另外model.py 223行附近，我这提示数组越界，改成pz = tonepattern[i+1][j] 就好了
